In [ ]:
import numpy as np
def fourier(N):
    i=0
    mat=[[]]
    for m in range(N):
        for k in range(N):
          mat.append(omega(k+i))
        i=i+1
    return mat
def omega(n):
    return np.exp((2*(np.pi) *J*k)/n)

In [ ]:
import numpy as np

def fourier(N):
    mat = np.zeros((N, N), dtype=complex)  # Initialize a 2D array with complex type
    for m in range(N):
        for k in range(N):
            mat[m, k] = omega(m, k, N)  # Call omega with m, k, and N
    return mat

def omega(m, k, N):
    return np.exp(-2j * np.pi * m * k / N)  # Fourier transform factor

# Example usage:
N = 4
F = fourier(N)
print(F)


[[ 1.0000000e+00+0.0000000e+00j  1.0000000e+00+0.0000000e+00j
   1.0000000e+00+0.0000000e+00j  1.0000000e+00+0.0000000e+00j]
 [ 1.0000000e+00+0.0000000e+00j  6.1232340e-17-1.0000000e+00j
  -1.0000000e+00-1.2246468e-16j -1.8369702e-16+1.0000000e+00j]
 [ 1.0000000e+00+0.0000000e+00j -1.0000000e+00-1.2246468e-16j
   1.0000000e+00+2.4492936e-16j -1.0000000e+00-3.6739404e-16j]
 [ 1.0000000e+00+0.0000000e+00j -1.8369702e-16+1.0000000e+00j
  -1.0000000e+00-3.6739404e-16j  5.5109106e-16-1.0000000e+00j]]


In [ ]:
c=np.array([[1],[0],[1],[0]])

In [ ]:
c

array([[1],
       [0],
       [1],
       [0]])

In [ ]:
y=F @ c # multiplication in numpy

In [ ]:
y

array([[2.+0.0000000e+00j],
       [0.-1.2246468e-16j],
       [2.+2.4492936e-16j],
       [0.-3.6739404e-16j]])

In [ ]:
# Fast fourier transform
def fft(x):
  return DMat(x)@F(x)@per(m)
def DMat(x):
  N=x/2
  D=[[]]
  for i in range(2):
    D.append(indenity(N))
    D.append(Dat(x))
  return D
def indenity(x):
  k= np.zeros((N, N), dtype=complex)
  for i in range(x):
    k[i][i]=1
  return k
def Dat(x):
  k= np.zeros((N, N), dtype=complex)
  for i in range(x):
    k[i][i]=omega(i)
  return k


In [ ]:
def fft(x):
  m=len(x)
  return DMat(m)@ F(x)@permutation_matrix(m)
def F(x):
  N=x//2
  Fa=fourier(N)
  Fb=np.zeros((N, N), dtype=complex)
  F1=np.hstack((Fa,Fb))
  F2=np.hstack((Fb,Fa))
  F=np.vstack((F1,F2))
  return F
def DMat(m):
    N = len(x)
    a=identity_matrix(N//2)
    b=D(N//2)
    DMat1=np.hstack((a,b))
    DMat2=np.hstack((a,-b))
    DMat=np.vstack((DMat1,DMat2))
    return DMat
def D(m):
    N = len(x)
    D = np.zeros((N, N), dtype=complex)
    for i in range(N):
        D[i, i] = omega(i, N)
    return D

def omega(k, N):
    return np.exp(-2j * np.pi * k / N)

def identity_matrix(N):
    return np.eye(N, dtype=complex)

def permutation_matrix(N):
    P = np.zeros((N, N), dtype=complex)
    for i in range(N):
        P[i, (i // 2) + (i % 2) * (N // 2)] = 1
    return P

# Example usage:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7], dtype=complex)
print("Input:", x)
result = fft(x)
print("FFT:", result)


Input: [0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 8

In [ ]:
import numpy as np

def fft(size):
    x = np.arange(size, dtype=complex)
    return DMat(size) @ F(size) @ permutation_matrix(size)

def F(m):
    if m == 1:
        return np.array([[1]], dtype=complex)
    N = m // 2
    Fa = F(N)
    Fb = np.zeros((N, N), dtype=complex)
    F1 = np.hstack((Fa, Fb))
    F2 = np.hstack((Fb, Fa))
    return np.vstack((F1, F2))

def DMat(n):
    size = n // 2
    S = np.zeros((size, size), dtype=complex)
    zerom = np.zeros((size, size), dtype=complex)

    # Fill the matrix with the appropriate values
    for j in range(size):
        for k in range(size):
            S[j, k] = np.exp(-2j * np.pi * j * k / n)

    top = np.hstack((S, zerom))
    bottom = np.hstack((zerom,S))
    second = np.vstack((top, bottom))
    print(second)
    return second
def D(N):
    D = np.zeros((N, N), dtype=complex)
    for i in range(N):
        D[i, i] = omega(i, 2 * N)  # Use 2 * N because we need to match the twiddle factors for FFT
    return D

def omega(k, N):
    return np.exp((-2j * np.pi * k )/ N)

def identity_matrix(N):
    return np.eye(N, dtype=complex)

def permutation_matrix(N):
    P = np.zeros((N, N), dtype=complex)
    for i in range(N):
        P[i, (i // 2) + (i % 2) * (N // 2)] = 1
    return P

# Example usage:
size = 4
print("Size:", size)
result = fft(size)
print("FFT:", result)


Size: 4
[[1.000000e+00+0.j 1.000000e+00+0.j 0.000000e+00+0.j 0.000000e+00+0.j]
 [1.000000e+00+0.j 6.123234e-17-1.j 0.000000e+00+0.j 0.000000e+00+0.j]
 [0.000000e+00+0.j 0.000000e+00+0.j 1.000000e+00+0.j 1.000000e+00+0.j]
 [0.000000e+00+0.j 0.000000e+00+0.j 1.000000e+00+0.j 6.123234e-17-1.j]]
FFT: [[1.000000e+00+0.j 0.000000e+00+0.j 1.000000e+00+0.j 0.000000e+00+0.j]
 [1.000000e+00+0.j 0.000000e+00+0.j 6.123234e-17-1.j 0.000000e+00+0.j]
 [0.000000e+00+0.j 1.000000e+00+0.j 0.000000e+00+0.j 1.000000e+00+0.j]
 [0.000000e+00+0.j 1.000000e+00+0.j 0.000000e+00+0.j 6.123234e-17-1.j]]


In [ ]:
import numpy as np


def fourier_matrix(m):



def d_mat(n):
    size = n // 2
    s = np.zeros((size, size), dtype=complex)
    zerom = np.zeros((size, size), dtype=complex)

    for j in range(size):
        for k in range(size):
            s[j, k] = np.exp(-2j * np.pi * j * k / size)

    top = np.hstack((s, zerom))
    bottom = np.hstack((zerom, -(s)))
    second = np.vstack((top, bottom))
    return second

# def d(N):
#     D = np.zeros((N, N), dtype=complex)
#     for i in range(N):
#         D[i, i] = omega(i, 2 * N)  # Use 2 * N because we need to match the twiddle factors for FFT
#     return D

# def omega(k, N):
#     return np.exp((-2j * np.pi * k )/ N)

def identity_matrix(N):
    return np.eye(N, dtype=complex)

def permutation_matrix(N):
    P = np.zeros((N, N), dtype=complex)
    for i in range(N):
        P[i, (i // 2) + (i % 2) * (N // 2)] = 1
    return P

# Example usage:
size = 4
f=f(size)
s=d_mat(size)

p=permutation_matrix(size)
print(f)
print(s)
print(p)
g=f@s@p
m=f@s
m=m@p
m=m@c
print("Size:", size)

print("FFT:", m)


[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]]
[[ 1.+0.0000000e+00j  1.+0.0000000e+00j  0.+0.0000000e+00j
   0.+0.0000000e+00j]
 [ 1.+0.0000000e+00j -1.-1.2246468e-16j  0.+0.0000000e+00j
   0.+0.0000000e+00j]
 [ 0.+0.0000000e+00j  0.+0.0000000e+00j -1.-0.0000000e+00j
  -1.-0.0000000e+00j]
 [ 0.+0.0000000e+00j  0.+0.0000000e+00j -1.-0.0000000e+00j
   1.+1.2246468e-16j]]
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]]
Size: 4
FFT: [[2.+0.0000000e+00j]
 [0.-1.2246468e-16j]
 [0.+0.0000000e+00j]
 [0.+0.0000000e+00j]]


In [ ]:
print(f)

[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]]


In [ ]:
y=result @ c

In [ ]:
y

array([[2.+0.j],
       [1.-1.j],
       [0.+0.j],
       [0.+0.j]])

In [ ]:
permutation_matrix(4)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [ ]:
c

array([[1],
       [0],
       [1],
       [0]])

In [ ]:
y

array([[2.+0.j],
       [1.-1.j],
       [0.+0.j],
       [0.+0.j]])

In [ ]:
import numpy as np

def fft(x):
    m, n = x.shape
    return DMat(m) @ F(m) @ permutation_matrix(m) @ x @ permutation_matrix(n)

def F(m):
    if m == 1:
        return np.array([[1]], dtype=complex)
    N = m // 2
    Fa = F(N)
    Fb = np.zeros((N, N), dtype=complex)
    F1 = np.hstack((Fa, Fb))
    F2 = np.hstack((Fb, Fa))
    return np.vstack((F1, F2))

def DMat(m):
    if m == 1:
        return np.array([[1]], dtype=complex)
    N = m
    a = identity_matrix(N // 2)
    b = D(N // 2)
    DMat1 = np.hstack((a, b))
    DMat2 = np.hstack((a, -b))
    return np.vstack((DMat1, DMat2))

def D(N):
    D = np.zeros((N, N), dtype=complex)
    for i in range(N):
        D[i, i] = omega(i, 2 * N)  # Use 2 * N because we need to match the twiddle factors for FFT
    return D

def omega(k, N):
    return np.exp(-2j * np.pi * k / N)

def identity_matrix(N):
    return np.eye(N, dtype=complex)

def permutation_matrix(N):
    P = np.zeros((N, N), dtype=complex)
    for i in range(N):
        P[i, (i // 2) + (i % 2) * (N // 2)] = 1
    return P

# Example usage:
x = np.array([[0, 1, 2, 3], [4, 5, 6, 7]], dtype=complex)
print("Input:")
print(x)
result = fft(x)
print("FFT:")
print(result)


Input:
[[0.+0.j 1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j 7.+0.j]]
FFT:
[[ 4.+0.j  8.+0.j  6.+0.j 10.+0.j]
 [-4.+0.j -4.+0.j -4.+0.j -4.+0.j]]


In [ ]:
import numpy as np

def fourier_matrix(n):
    # Create an n x n Fourier matrix
    F = np.zeros((n, n), dtype=complex)

    # Fill the matrix with the appropriate values
    for j in range(n):
        for k in range(n):
            F[j, k] = np.exp(-2j * np.pi * j * k / n)

    return F

def calculate_identity(size):
    # Create an identity matrix of given size
    return np.eye(size, dtype=complex)

def diagonal_matrices(n):
    size = n // 2
    D = np.zeros((size, size), dtype=complex)
    Dne = np.zeros((size, size), dtype=complex)
    for j in range(size):
        D[j, j] = np.exp(-2j * np.pi * j / n)
        Dne[j, j] = -np.exp(-2j * np.pi * j / n)
    return D, Dne

def first_matrix(n):
    size = n // 2
    identity = calculate_identity(size)
    D, Dne = diagonal_matrices(n)

    # Stack matrices vertically and horizontally to form the 2x2 block matrix
    top = np.hstack((identity, D))
    bottom = np.hstack((identity, Dne))

    M = np.vstack((top, bottom))
    print(M)
    return M

def second_matrix(n):
    size = n // 2
    S = np.zeros((size, size), dtype=complex)
    zerom = np.zeros((size, size), dtype=complex)

    # Fill the matrix with the appropriate values
    for j in range(size):
        for k in range(size):
            S[j, k] = np.exp(-2j * np.pi * j * k / size)

    top = np.hstack((S, zerom))
    bottom = np.hstack((zerom,S))
    second = np.vstack((top, bottom))
    print(second)
    return second
def permutation_matrix(N):
    P = np.zeros((N, N), dtype=complex)
    for i in range(N):
        P[i, (i // 2) + (i % 2) * (N // 2)] = 1
    return P


# Example usage
n = 8# Size of the Fourier matrix
F = fourier_matrix(n)
c = np.array([[1], [0], [1], [0],[1], [0], [1], [0]])  # Column vector

P = permutation_matrix(n)

print("Fourier Matrix (F):")
print(F)

print("\nFirst matrix (M):")
f=first_matrix(n)
print("\nSecond matrix:")
s=second_matrix(n)
print("permutation")
print(P)
# Correct way to apply the permutation matrix
final = f @ s  # Multiply the first and second matrices
final = final @ P  # Apply permutation matrix to the result
print("\nFinal result after applying permutation (f @ s @ P):")
y = final @ c  # Matrix multiplication
 # Multiply by column vector c

Fourier Matrix (F):
[[ 1.00000000e+00+0.00000000e+00j  1.00000000e+00+0.00000000e+00j
   1.00000000e+00+0.00000000e+00j  1.00000000e+00+0.00000000e+00j
   1.00000000e+00+0.00000000e+00j  1.00000000e+00+0.00000000e+00j
   1.00000000e+00+0.00000000e+00j  1.00000000e+00+0.00000000e+00j]
 [ 1.00000000e+00+0.00000000e+00j  7.07106781e-01-7.07106781e-01j
   6.12323400e-17-1.00000000e+00j -7.07106781e-01-7.07106781e-01j
  -1.00000000e+00-1.22464680e-16j -7.07106781e-01+7.07106781e-01j
  -1.83697020e-16+1.00000000e+00j  7.07106781e-01+7.07106781e-01j]
 [ 1.00000000e+00+0.00000000e+00j  6.12323400e-17-1.00000000e+00j
  -1.00000000e+00-1.22464680e-16j -1.83697020e-16+1.00000000e+00j
   1.00000000e+00+2.44929360e-16j  3.06161700e-16-1.00000000e+00j
  -1.00000000e+00-3.67394040e-16j -4.28626380e-16+1.00000000e+00j]
 [ 1.00000000e+00+0.00000000e+00j -7.07106781e-01-7.07106781e-01j
  -1.83697020e-16+1.00000000e+00j  7.07106781e-01-7.07106781e-01j
  -1.00000000e+00-3.67394040e-16j  7.07106781e-01+7.0

In [ ]:
print(y)

[[ 4.00000000e+00+0.00000000e+00j]
 [ 1.00000000e+00-2.41421356e+00j]
 [-1.83697020e-16-2.22044605e-16j]
 [ 1.00000000e+00-4.14213562e-01j]
 [ 0.00000000e+00+0.00000000e+00j]
 [ 1.00000000e+00+4.14213562e-01j]
 [ 7.26747174e-17-1.11022302e-16j]
 [ 1.00000000e+00+2.41421356e+00j]]


In [ ]:
import numpy as np

def fourier_matrix(n):
    # Create an n x n Fourier matrix
    F = np.zeros((n, n), dtype=complex)

    # Fill the matrix with the appropriate values
    for j in range(n):
        for k in range(n):
            F[j, k] = np.exp(-2j * np.pi * j * k / n)

    return F

def calculate_identity(size):
    # Create an identity matrix of given size
    return np.eye(size, dtype=complex)

def diagonal_matrices(n):
    size = n // 2
    D = np.zeros((size, size), dtype=complex)
    Dne = np.zeros((size, size), dtype=complex)
    for j in range(size):
        D[j, j] = np.exp(-2j * np.pi * j / n)
        Dne[j, j] = -np.exp(-2j * np.pi * j / n)
    return D, Dne

def first_matrix(n):
    size = n // 2
    identity = calculate_identity(size)
    D, Dne = diagonal_matrices(n)

    # Stack matrices vertically and horizontally to form the 2x2 block matrix
    top = np.hstack((identity, D))
    bottom = np.hstack((identity, Dne))

    M = np.vstack((top, bottom))
    print(M)
    return M

def second_matrix(n):
    size = n // 2
    S = np.zeros((size, size), dtype=complex)
    zerom = np.zeros((size, size), dtype=complex)

    # Fill the matrix with the appropriate values
    for j in range(size):
        for k in range(size):
            S[j, k] = np.exp(-2j * np.pi * j * k / size)

    top = np.hstack((S, zerom))
    bottom = np.hstack((zerom,S))
    second = np.vstack((top, bottom))
    print(second)
    return second
def permutation_matrix(N):
    P = np.zeros((N, N), dtype=complex)
    for i in range(N):
        P[i, (i // 2) + (i % 2) * (N // 2)] = 1
    return P


# Example usage
n = 4 # Size of the Fourier matrix
F = fourier_matrix(n)
c = np.array([[1], [0], [1], [0]])  # Column vector
y = F @ c  # Matrix multiplication
P = permutation_matrix(n)

print("Fourier Matrix (F):")
print(F)
print("\nResult of F @ c (y):")
print(y)
print("\nFirst matrix (M):")
f=first_matrix(n)
print("\nSecond matrix:")
s=second_matrix(n)
print("permutation")
print(P)
# Correct way to apply the permutation matrix
final = f @ s  # Multiply the first and second matrices
final = final @ P  # Apply permutation matrix to the result
print("\nFinal result after applying permutation (f @ s @ P):")
print(final @ c)  # Multiply by column vector c

Fourier Matrix (F):
[[ 1.0000000e+00+0.0000000e+00j  1.0000000e+00+0.0000000e+00j
   1.0000000e+00+0.0000000e+00j  1.0000000e+00+0.0000000e+00j]
 [ 1.0000000e+00+0.0000000e+00j  6.1232340e-17-1.0000000e+00j
  -1.0000000e+00-1.2246468e-16j -1.8369702e-16+1.0000000e+00j]
 [ 1.0000000e+00+0.0000000e+00j -1.0000000e+00-1.2246468e-16j
   1.0000000e+00+2.4492936e-16j -1.0000000e+00-3.6739404e-16j]
 [ 1.0000000e+00+0.0000000e+00j -1.8369702e-16+1.0000000e+00j
  -1.0000000e+00-3.6739404e-16j  5.5109106e-16-1.0000000e+00j]]

Result of F @ c (y):
[[2.+0.0000000e+00j]
 [0.-1.2246468e-16j]
 [2.+2.4492936e-16j]
 [0.-3.6739404e-16j]]

First matrix (M):
[[ 1.000000e+00+0.j  0.000000e+00+0.j  1.000000e+00+0.j  0.000000e+00+0.j]
 [ 0.000000e+00+0.j  1.000000e+00+0.j  0.000000e+00+0.j  6.123234e-17-1.j]
 [ 1.000000e+00+0.j  0.000000e+00+0.j -1.000000e+00-0.j  0.000000e+00+0.j]
 [ 0.000000e+00+0.j  1.000000e+00+0.j  0.000000e+00+0.j -6.123234e-17+1.j]]

Second matrix:
[[ 1.+0.0000000e+00j  1.+0.0000000e+